# Generated by Django 5.0.7 on 2024-08-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_url',
            field=models.URLField(null=True),
        ),
    ]
