# Generated by Django 5.0.7 on 2024-08-05 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techblog', '0006_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
    ]
